# Listen to the specified socket for remote control connections. Note
# that this will apply to all kitty instances.
listen_on unix:/tmp/kitty

tab_bar_filter session:~ or session:^$

map ctrl+shift+p launch --type=overlay --title "Project Selector" /bin/zsh -c "$HOME/.config/kitty/scripts/kitty-list-sessions.sh"
map kitty_mod+. launch --type=background kitten quick-access-terminal
