# Your kitty config goes here
# ....
# 

# Listen to the specified socket for remote control connections. Note
# that this will apply to all kitty instances.
listen_on unix:/tmp/kitty

tab_bar_filter session:~ or session:^$

map ctrl+shift+p launch --type=background  --title "Project Selector" $HOME/.config/kitty/scripts/kitty-session-float.sh
map ctrl+shift+s save_as_session --relocatable --use-foreground-process --match=session:. .
map ctrl+shift+x close_session .

# You config continues....